import { getActiveEvents, getFormats, getEventsForVenue } from "@/lib/events";
import { generateIcsString } from "@/lib/ical";
import { config } from "@/lib/config";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

/**
 * Subscribable ICS feed. Accepts optional filter query params so the same
 * URL can serve the homepage's full feed *or* a per-user-narrowed slice
 * (e.g. only Commander events within 10 miles of Philly, this week):
 *
 *   /calendar
 *   /calendar?format=Commander&radius=10&days=7
 *
 * No-param requests preserve the original "all active events, all upcoming"
 * behavior byte-for-byte so existing webcal:// subscribers don't break.
 */
export async function GET(request: Request) {
  const sp = new URL(request.url).searchParams;

  // Validate format against the live formats list — new formats added in the
  // DB auto-work without code edits, and unknown values are silently ignored.
  const requestedFormat = sp.get("format")?.trim();
  const format = requestedFormat && getFormats().includes(requestedFormat) ? requestedFormat : undefined;

  const days = clampInt(sp.get("days"), 1, 365);
  const radius = clampInt(sp.get("radius"), 1, 500);
  const lat = parseFloatOr(sp.get("lat"), config.location.lat);
  const lng = parseFloatOr(sp.get("lng"), config.location.lng);
  // Single-venue scope. Trumps radius — when set, the feed lists only
  // events at exactly this venue. Mirrors the venue page's listing.
  const venue = sp.get("venue")?.trim() || undefined;
  // RCQ-only filter. Title-pattern-based — see lib/events.ts for the match.
  const rcq = sp.get("rcq") === "1";
  // cEDH-only filter. Same shape as RCQ — a sub-format signal that lives
  // in the title rather than the format column.
  const cedh = sp.get("cedh") === "1";

  let events;
  if (venue) {
    // Pull a wider per-venue slice (venues rarely run > 200 in 365 days)
    // and apply format/days client-side; getEventsForVenue already excludes
    // past events and respects status/visibility/cancelled.
    const all = getEventsForVenue(venue, 1000);
    const fromISO = todayISO();
    const toISO = days != null ? addDaysISO(days) : null;
    events = all.filter((ev) => {
      if (format && ev.format !== format) return false;
      if (rcq && !(ev.title.includes("RCQ") || ev.title.includes("Regional Championship Qualifier"))) return false;
      if (cedh && !/(^|[^a-z])(cedh|competitive\s+(edh|commander))($|[^a-z])/i.test(ev.title)) return false;
      if (toISO && (ev.date < fromISO || ev.date > toISO)) return false;
      return true;
    });
  } else {
    const filters: Parameters<typeof getActiveEvents>[0] = {};
    if (format) filters.format = format;
    if (rcq) filters.rcq = true;
    if (cedh) filters.cedh = true;
    if (days != null) {
      filters.from = todayISO();
      filters.to = addDaysISO(days);
    }
    if (radius != null) {
      filters.radiusMiles = radius;
      filters.centerLat = lat;
      filters.centerLng = lng;
    }
    events = getActiveEvents(filters);
  }

  const city = config.location.city;
  const isFiltered = venue || format || days != null || radius != null || rcq || cedh;
  const subTag = cedh ? " · cEDH" : rcq ? " · RCQs" : "";
  const calName = isFiltered
    ? venue
      ? `MTG ${format ?? "Events"} — ${venue}${subTag}${days != null ? ` · ${days}d` : ""}`
      : `MTG ${format ?? "Events"} — ${city}${radius != null ? ` (${radius}mi)` : ""}${subTag}${days != null ? ` · ${days}d` : ""}`
    : config.output.calendarName;
  const formatDesc = cedh
    ? `${format ?? "all formats"} (cEDH only)`
    : rcq
      ? `${format ?? "all formats"} (RCQs only)`
      : (format ?? "all formats");
  const calDesc = isFiltered
    ? venue
      ? `Filtered: ${formatDesc} at ${venue}, ${days != null ? `next ${days} days` : "all upcoming"}. Generated by PlayIRL.GG.`
      : `Filtered: ${formatDesc}, ${radius != null ? `${radius} mi from ${city}` : "all distances"}, ${days != null ? `next ${days} days` : "all upcoming"}. Generated by PlayIRL.GG.`
    : config.output.calendarDescription;

  const ics = generateIcsString(events, calName, calDesc);

  const venueSlug = venue ? venue.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") : null;
  const subSlug = cedh ? "-cedh" : rcq ? "-rcq" : "";
  const filename = `mtg-${format ?? "events"}${subSlug}${venueSlug ? `-${venueSlug}` : ""}${radius != null && !venue ? `-${radius}mi` : ""}${days != null ? `-${days}d` : ""}.ics`;

  return new NextResponse(ics, {
    headers: {
      "Content-Type": "text/calendar; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "public, max-age=3600",
    },
  });
}

function clampInt(raw: string | null, min: number, max: number): number | null {
  if (raw == null || raw === "") return null;
  const n = parseInt(raw, 10);
  if (!Number.isFinite(n)) return null;
  return Math.max(min, Math.min(max, n));
}

function parseFloatOr(raw: string | null, fallback: number): number {
  if (raw == null || raw === "") return fallback;
  const n = parseFloat(raw);
  return Number.isFinite(n) ? n : fallback;
}

function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}

function addDaysISO(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}
